### ISSUE TITLE
Launch on tesnet / sandbox

### ISSUE THREAD

**Issue by EvgeniiaVak** [btrccts/btrccts#158]
`ccxt` supports running on testnet via [exchange.set_sandbox_mode(True)](https://github.com/ccxt/ccxt/blob/495191b3082147cb7707656e2a33c74052264c6b/python/ccxt/base/exchange.py#L460)

Is it possible to use tesnet with [btrccts](https://github.com/btrccts/btrccts) (I did not find any such setting)? 

I can implement and send a PR if needed, I think it can be another context, which is very similar to live, but sets up the sandbox:
```python
class SandboxContext(LiveContext):
...
```

**Comment by brandsimon** [comment]
@EvgeniiaVak 
Since Sandbox mode is an exchange specific feature, it is currently supported in live mode.
In live mode `context.create_exchange` just returns an instance of a ccxt exchange, so you can call `set_sandbox_mode` on the result. To toggle between behavior, you can use `configure_argparser` of the Algorithm and only call `set_sandbox_mode` depending on the argument.

If this does not suit your needs, regarding your PR, I think a cleaner approach would be to add `setSandboxMode` to the ccxt `has` API method metainfo and add a method to the `BacktestExchangeBase`.
Then the `SandboxContext` (or probably use LiveContext with a parameter) could check the support of the sandbox mode and throw, if not supported.

Does this solve your issue?

**Comment by EvgeniiaVak** [comment]
Yes, that makes sense, thanks. I'll try with set_sandbox_mode inside
Algorithm. 👍
